.c.obj :
	$(CC) $(CFLAGS) $*.c 
#
# Compilers:
#
CC = bcc
#
# cc flags
#
CFLAGS = -c -I../src -ml 
#
LDFLAGS = -L../src -ml
LIBS = libplotsub.lib libdevices.lib libutils.lib
#
tstc : tstc.obj
	$(CC) $(LDFLAGS) tstc.obj $(LIBS)
contc : contc.obj
	$(CC) $(LDFLAGS) contc.obj $(LIBS)
clean :
	- del contc.exe
	- del tstc.exe
	- del *.bak
	- del *.obj

